import { db } from "./index";
import * as schema from "./schema";

const brl = (reais: number) => reais * 100;

const motorcycles: (typeof schema.motorcycles.$inferInsert)[] = [
  {
    slug: "nightster",
    name: "Nightster",
    family: "Sportster",
    year: 2025,
    price: brl(69900),
    tagline: "O ponto de partida escuro.",
    description:
      "Motor Revolution Max 975T, silhueta enxuta e postura baixa. A Nightster é a porta de entrada mais honesta da linha: leve o suficiente para o trânsito, brava o suficiente para a estrada aberta.",
    engine: "Revolution Max 975T",
    displacement: 975,
    power: 91,
    torque: 95,
    weight: 221,
    seatHeight: 705,
    fuel: 11.7,
    consumption: 20.4,
    colors: ["Vivid Black", "Dark Billiard Gray", "Blood Orange"],
    image: "/images/nightster.jpg",
    gallery: ["/images/nightster.jpg", "/images/detail-exhaust.jpg"],
    featured: true,
    stock: 4,
  },
  {
    slug: "sportster-s",
    name: "Sportster S",
    family: "Sportster",
    year: 2025,
    price: brl(89900),
    tagline: "Torque imediato, zero cerimônia.",
    description:
      "Revolution Max 1250T com 121 cv e escapamento alto na lateral. Chassi rígido, freio Brembo e um comportamento que responde antes de você terminar o pensamento.",
    engine: "Revolution Max 1250T",
    displacement: 1252,
    power: 121,
    torque: 125,
    weight: 228,
    seatHeight: 755,
    fuel: 11.8,
    consumption: 19.2,
    colors: ["Vivid Black", "Aurora Blue Denim", "Blood Orange"],
    image: "/images/sportster-s.jpg",
    gallery: ["/images/sportster-s.jpg", "/images/lifestyle-night.jpg"],
    featured: true,
    stock: 3,
  },
  {
    slug: "low-rider-s",
    name: "Low Rider S",
    family: "Softail",
    year: 2025,
    price: brl(129900),
    tagline: "Performance cruiser sem disfarce.",
    description:
      "Milwaukee-Eight 117 em um chassi Softail baixo, com guidão moto-bar e pintura sóbria. O equilíbrio raro entre atitude de custom e ritmo de esportiva.",
    engine: "Milwaukee-Eight 117",
    displacement: 1923,
    power: 106,
    torque: 168,
    weight: 306,
    seatHeight: 720,
    fuel: 18.9,
    consumption: 16.8,
    colors: ["Vivid Black", "Billiard Gray", "Brilliant Red"],
    image: "/images/low-rider-s.jpg",
    gallery: ["/images/low-rider-s.jpg", "/images/low-rider-s-red.jpg"],
    featured: true,
    stock: 2,
  },
  {
    slug: "fat-boy-114",
    name: "Fat Boy 114",
    family: "Softail",
    year: 2025,
    price: brl(139900),
    tagline: "O ícone de alumínio maciço.",
    description:
      "Rodas Lakester, pneu dianteiro largo e tanque com faixa cromada: a Fat Boy é reconhecida antes de ser ouvida. Milwaukee-Eight 114 com entrega linear e presença total.",
    engine: "Milwaukee-Eight 114",
    displacement: 1868,
    power: 94,
    torque: 155,
    weight: 317,
    seatHeight: 675,
    fuel: 18.9,
    consumption: 17.4,
    colors: ["Vivid Black", "Whiskey Fire", "Billiard Gray"],
    image: "/images/fat-boy.jpg",
    gallery: ["/images/fat-boy.jpg", "/images/lifestyle-desert.jpg"],
    featured: true,
    stock: 3,
  },
  {
    slug: "breakout-117",
    name: "Breakout 117",
    family: "Softail",
    year: 2025,
    price: brl(145900),
    tagline: "Dragster de rua, licença para arrastar.",
    description:
      "Tanque alongado, roda dianteira de 21 polegadas e o maior motor da linha Softail. Feita para acelerar em linha reta e ser olhada em cada semáforo.",
    engine: "Milwaukee-Eight 117",
    displacement: 1923,
    power: 106,
    torque: 168,
    weight: 305,
    seatHeight: 665,
    fuel: 18.9,
    consumption: 16.5,
    colors: ["Vivid Black", "Iron Horse Metallic", "Brilliant Red"],
    image: "/images/breakout.jpg",
    gallery: ["/images/breakout.jpg", "/images/detail-exhaust.jpg"],
    featured: false,
    stock: 2,
  },
  {
    slug: "heritage-classic",
    name: "Heritage Classic",
    family: "Softail",
    year: 2025,
    price: brl(149900),
    tagline: "Viagem com sotaque clássico.",
    description:
      "Para-brisa removível, alforjes de couro e faróis auxiliares. A Heritage combina a estética dos anos 50 com suspensão e freios de hoje — pronta para dois dias de estrada.",
    engine: "Milwaukee-Eight 114",
    displacement: 1868,
    power: 94,
    torque: 155,
    weight: 330,
    seatHeight: 680,
    fuel: 18.9,
    consumption: 17.1,
    colors: ["White Onyx Pearl", "Iron Horse Metallic", "Whiskey Fire"],
    image: "/images/heritage-classic.jpg",
    gallery: ["/images/heritage-classic.jpg", "/images/lifestyle-desert.jpg"],
    featured: false,
    stock: 3,
  },
  {
    slug: "pan-america-1250-special",
    name: "Pan America 1250 Special",
    family: "Adventure",
    year: 2025,
    price: brl(129900),
    tagline: "Asfalto acaba, o percurso continua.",
    description:
      "Suspensão semiativa com Adaptive Ride Height, 150 cv e modos de pilotagem. A Harley que troca o cromado pela lama sem pedir desculpas.",
    engine: "Revolution Max 1250",
    displacement: 1252,
    power: 150,
    torque: 128,
    weight: 258,
    seatHeight: 850,
    fuel: 21.2,
    consumption: 18.6,
    colors: ["Vivid Black", "Billiard Gray", "Baja Orange"],
    image: "/images/pan-america.jpg",
    gallery: ["/images/pan-america.jpg", "/images/pan-america-2.jpg", "/images/lifestyle-mountain.jpg"],
    featured: false,
    stock: 4,
  },
  {
    slug: "street-glide",
    name: "Street Glide",
    family: "Touring",
    year: 2025,
    price: brl(189900),
    tagline: "Bat-wing, som alto, horizonte longo.",
    description:
      "Carenagem bat-wing redesenhada, painel de 12,3 polegadas e Milwaukee-Eight 117. Cruzeiro de longa distância com o perfil mais reconhecível do asfalto.",
    engine: "Milwaukee-Eight 117",
    displacement: 1923,
    power: 108,
    torque: 176,
    weight: 371,
    seatHeight: 720,
    fuel: 22.7,
    consumption: 15.7,
    colors: ["Vivid Black", "Brilliant Red", "White Onyx Pearl"],
    image: "/images/street-glide.jpg",
    gallery: ["/images/street-glide.jpg", "/images/street-glide-red.jpg"],
    featured: false,
    stock: 2,
  },
  {
    slug: "road-glide",
    name: "Road Glide",
    family: "Touring",
    year: 2025,
    price: brl(199900),
    tagline: "Carenagem fixa. Vento domado.",
    description:
      "Shark-nose montada no chassi: a direção fica leve mesmo em velocidade de cruzeiro. Infoentretenimento Skyline OS, três modos de pilotagem e alforjes rígidos.",
    engine: "Milwaukee-Eight 117",
    displacement: 1923,
    power: 108,
    torque: 176,
    weight: 374,
    seatHeight: 720,
    fuel: 22.7,
    consumption: 15.4,
    colors: ["Vivid Black", "Billiard Gray", "Blue Burst"],
    image: "/images/road-glide.jpg",
    gallery: ["/images/road-glide.jpg", "/images/lifestyle-night.jpg"],
    featured: false,
    stock: 2,
  },
  {
    slug: "cvo-road-glide-st",
    name: "CVO Road Glide ST",
    family: "CVO",
    year: 2025,
    price: brl(389900),
    tagline: "O topo absoluto da fábrica.",
    description:
      "Milwaukee-Eight 121 High Output, acabamento CVO exclusivo e áudio Rockford Fosgate. Produção limitada, numeração própria e a maior potência de série da marca.",
    engine: "Milwaukee-Eight 121 High Output",
    displacement: 1977,
    power: 129,
    torque: 190,
    weight: 366,
    seatHeight: 730,
    fuel: 22.7,
    consumption: 14.8,
    colors: ["Raven Fade", "Dark Platinum Fade"],
    image: "/images/cvo-road-glide.jpg",
    gallery: ["/images/cvo-road-glide.jpg", "/images/detail-exhaust.jpg"],
    featured: false,
    stock: 1,
  },
];

const parts: (typeof schema.parts.$inferInsert)[] = [
  {
    slug: "capacete-vanocker-x09",
    name: "Capacete Vanocker X09 Matte",
    category: "Capacetes",
    price: brl(2490),
    description: "Casco em fibra, viseira solar interna e forro removível lavável.",
    image: "/images/part-helmet.jpg",
  },
  {
    slug: "jaqueta-couro-bar-shield",
    name: "Jaqueta de Couro Bar & Shield",
    category: "Vestuário",
    price: brl(4290),
    description: "Couro bovino curtido, forro térmico removível e proteções nos ombros.",
    image: "/images/part-jacket.jpg",
  },
  {
    slug: "luvas-iron-grip",
    name: "Luvas Iron Grip",
    category: "Vestuário",
    price: brl(690),
    description: "Palma em gel, reforço nos nós dos dedos e ponta compatível com touch.",
    image: "/images/part-gloves.jpg",
  },
  {
    slug: "botas-riverton",
    name: "Botas Riverton Leather",
    category: "Vestuário",
    price: brl(1890),
    description: "Cano médio, solado antiderrapante e reforço na canela.",
    image: "/images/part-boots.jpg",
  },
  {
    slug: "alforje-couro-heritage",
    name: "Alforje de Couro Heritage",
    category: "Bagagem",
    price: brl(3390),
    description: "Par de alforjes throw-over em couro legítimo, 22 litros por lado.",
    image: "/images/part-saddlebag.jpg",
  },
  {
    slug: "retrovisor-cromado-round",
    name: "Retrovisor Cromado Round 3\"",
    category: "Custom",
    price: brl(540),
    description: "Par de retrovisores redondos cromados, haste curta estilo shorty.",
    image: "/images/part-mirror.jpg",
  },
  {
    slug: "escapamento-slip-on-torque",
    name: "Escapamento Slip-On Torque",
    category: "Performance",
    price: brl(6790),
    description: "Ponteiras 4\" cromadas, ganho de torque em baixa e som mais grave.",
    image: "/images/part-exhaust.jpg",
  },
  {
    slug: "oleo-sintetico-20w50",
    name: "Óleo Sintético 20W50 V-Twin",
    category: "Manutenção",
    price: brl(189),
    description: "Litro de óleo sintético formulado para motores V-Twin refrigerados a ar.",
    image: "/images/part-oil.jpg",
  },
];

const dealers: (typeof schema.dealers.$inferInsert)[] = [
  {
    name: "Iron & Oak São Paulo",
    city: "São Paulo",
    state: "SP",
    address: "Av. Brigadeiro Faria Lima, 2140 — Jardim Paulistano",
    phone: "(11) 4002-8922",
    hours: "Seg a Sex 9h–19h · Sáb 9h–16h",
    image: "/images/showroom-1.jpg",
  },
  {
    name: "Iron & Oak Rio de Janeiro",
    city: "Rio de Janeiro",
    state: "RJ",
    address: "Av. das Américas, 4790 — Barra da Tijuca",
    phone: "(21) 4002-8933",
    hours: "Seg a Sex 9h–19h · Sáb 9h–15h",
    image: "/images/showroom-2.jpg",
  },
  {
    name: "Iron & Oak Curitiba",
    city: "Curitiba",
    state: "PR",
    address: "Av. Sete de Setembro, 5390 — Batel",
    phone: "(41) 4002-8944",
    hours: "Seg a Sex 9h–18h30 · Sáb 9h–14h",
    image: "/images/showroom-1.jpg",
  },
  {
    name: "Iron & Oak Belo Horizonte",
    city: "Belo Horizonte",
    state: "MG",
    address: "Av. Nossa Senhora do Carmo, 1300 — Sion",
    phone: "(31) 4002-8955",
    hours: "Seg a Sex 9h–18h · Sáb 9h–13h",
    image: "/images/showroom-2.jpg",
  },
  {
    name: "Iron & Oak Porto Alegre",
    city: "Porto Alegre",
    state: "RS",
    address: "Av. Carlos Gomes, 222 — Boa Vista",
    phone: "(51) 4002-8966",
    hours: "Seg a Sex 9h–18h · Sáb 9h–13h",
    image: "/images/showroom-1.jpg",
  },
];

const posts: (typeof schema.posts.$inferInsert)[] = [
  {
    slug: "milwaukee-eight-117-o-que-mudou",
    title: "Milwaukee-Eight 117: o que realmente mudou",
    excerpt:
      "Cabeçotes novos, admissão redesenhada e mais torque abaixo de 3.000 rpm. Abrimos o motor para entender onde está o ganho.",
    category: "Engenharia",
    author: "Rafael Nunes",
    image: "/images/detail-exhaust.jpg",
    readMinutes: 7,
    publishedAt: "2026-07-28",
    content:
      "O 117 não é apenas um 114 com mais curso. A mudança começa na admissão: o corpo de borboleta maior e o novo formato do coletor deixam o enchimento dos cilindros mais eficiente justo na faixa onde a moto é usada de verdade — entre 2.000 e 3.500 rpm.\n\nNa prática, isso significa menos trocas de marcha em subida e uma retomada mais limpa a 100 km/h. O ganho declarado de potência é modesto no papel, mas a curva de torque é quase uma reta: 90% do pico está disponível a partir de 2.250 rpm.\n\nO segundo ponto é térmico. Os novos dutos de refrigeração e o gerenciamento eletrônico do ventilador reduziram a temperatura percebida na perna direita em trânsito parado — a reclamação mais comum entre proprietários de Touring em capitais brasileiras.\n\nSe você vem de um Twin Cam, a diferença mais evidente não é velocidade máxima. É o quanto a moto deixou de exigir esforço para andar rápido.",
  },
  {
    slug: "primeira-harley-como-escolher",
    title: "Primeira Harley: como escolher sem se arrepender",
    excerpt:
      "Altura do assento, peso e tipo de uso pesam mais do que cilindrada. Um roteiro honesto para o primeiro modelo.",
    category: "Guia",
    author: "Marina Prado",
    image: "/images/nightster.jpg",
    readMinutes: 6,
    publishedAt: "2026-07-14",
    content:
      "A pergunta errada é 'qual a maior moto que eu consigo pilotar'. A pergunta certa é 'qual moto eu vou querer tirar da garagem numa terça-feira'.\n\nComece pela altura do assento. Com os dois pés no chão e os joelhos levemente flexionados, você resolve 80% da insegurança inicial. A Nightster, com 705 mm, é o caso mais amigável da linha atual.\n\nDepois, o peso em movimento. Uma Touring de 370 kg é estável a 110 km/h e cansativa numa manobra de estacionamento. Se seu uso é urbano, o par Sportster resolve melhor.\n\nPor último, o uso real. Anote quantos quilômetros você rodou no último ano e em que tipo de via. Se a resposta for 'cidade, 40 km por dia', comprar uma CVO é pagar por uma capacidade que você não vai usar.\n\nAgende um test ride em dois modelos no mesmo dia. A comparação direta responde mais rápido que qualquer tabela.",
  },
  {
    slug: "rota-serra-do-rio-do-rastro",
    title: "Rota: Serra do Rio do Rastro em dois dias",
    excerpt:
      "424 km de São Paulo até o mirante, com paradas testadas e o trecho que você deve evitar de manhã.",
    category: "Rotas",
    author: "Caio Bertoldi",
    image: "/images/lifestyle-mountain.jpg",
    readMinutes: 9,
    publishedAt: "2026-06-30",
    content:
      "A subida tem 12 km e 284 curvas. O que ninguém conta é que o melhor horário não é o amanhecer: a neblina fecha o mirante até quase 10h em boa parte do ano.\n\nDia 1 — Saída de São Paulo pela Régis Bittencourt, parada em Registro para combustível e almoço em Joinville. Evite a BR-101 depois das 17h; o tráfego de caminhões no trecho de Itajaí anula qualquer ganho de tempo.\n\nDia 2 — Bom Jardim da Serra é a base certa para dormir. Suba a serra por volta das 10h30, desça devagar e reserve a tarde para a estrada de terra até a Cascata do Rio dos Bugres — Pan America agradece, Softail sofre.\n\nLeve capa de chuva mesmo em julho. A temperatura no alto cai 10 °C em relação ao litoral e o vento lateral no mirante é constante.",
  },
  {
    slug: "manutencao-preventiva-cada-8000-km",
    title: "O que revisar a cada 8.000 km",
    excerpt:
      "Checklist objetivo de manutenção preventiva para V-Twin refrigerado a ar rodando em clima tropical.",
    category: "Manutenção",
    author: "Rafael Nunes",
    image: "/images/part-oil.jpg",
    readMinutes: 5,
    publishedAt: "2026-06-12",
    content:
      "Óleo do motor e filtro são o básico, mas em clima tropical o intervalo real é menor que o do manual americano. Trânsito lento e 35 °C degradam o lubrificante mais rápido.\n\nChecklist a cada 8.000 km: óleo e filtro do motor, nível do óleo primário e da transmissão, tensão e lubrificação da correia, pastilhas de freio (mínimo 2 mm), fluido de freio (troca a cada 2 anos), pressão e desgaste dos pneus, aperto dos parafusos do guidão e da suspensão.\n\nDuas verificações que quase todo mundo esquece: a folga do cabo de embreagem — que muda com o calor — e a bateria. Motos que ficam paradas mais de duas semanas precisam de mantenedor, não de recarga emergencial.",
  },
  {
    slug: "custom-legal-o-que-pode",
    title: "Custom legal: o que pode e o que reprova na vistoria",
    excerpt:
      "Escapamento, guidão, iluminação e placa. O limite entre personalização e multa, item por item.",
    category: "Custom",
    author: "Marina Prado",
    image: "/images/low-rider-s-red.jpg",
    readMinutes: 8,
    publishedAt: "2026-05-22",
    content:
      "Personalizar não é ilegal. Descaracterizar é. A diferença está no que consta no CRLV e no que altera o comportamento ou a segurança da moto.\n\nEscapamento: substituição é permitida desde que o ruído fique dentro do limite e o catalisador seja mantido. Ponteira 'reta' sem catalisador reprova.\n\nGuidão: alterações que mudem a posição de pilotagem exigem laudo de engenheiro e anotação no documento. Ape hangers muito altos costumam reprovar por interferir na visibilidade dos comandos.\n\nIluminação: LED substituto é aceito se mantiver cor, intensidade e alcance homologados. Faróis auxiliares azuis ou estroboscópicos são infração.\n\nPlaca: precisa estar na vertical, na posição original. Suporte lateral 'side mount' é uma das causas mais comuns de autuação em blitz.",
  },
  {
    slug: "financiamento-vs-consorcio",
    title: "Financiamento ou consórcio: a conta real",
    excerpt:
      "Comparamos o custo total de uma Low Rider S nas duas modalidades, com taxas de mercado de 2026.",
    category: "Finanças",
    author: "Caio Bertoldi",
    image: "/images/low-rider-s.jpg",
    readMinutes: 6,
    publishedAt: "2026-05-05",
    content:
      "Numa Low Rider S de R$ 129.900 com 30% de entrada, o financiamento em 36 meses a 1,49% ao mês custa cerca de R$ 21 mil em juros. O consórcio, com taxa de administração de 16% e prazo de 60 meses, custa aproximadamente R$ 20,8 mil em taxas — mas sem a moto na garagem no primeiro mês.\n\nA conta muda com a intenção. Se você vai usar a moto agora, financiamento é o único caminho e o ponto de atenção é a taxa: cada 0,2% ao mês representa cerca de R$ 3 mil no total.\n\nSe a compra é para 2027, o consórcio é mais barato que guardar dinheiro em poupança e evita a tentação de gastar a reserva.\n\nO erro mais comum é alongar o prazo para caber na parcela. Em 48 meses, o mesmo contrato passa dos R$ 29 mil em juros.",
  },
];

async function seed() {
  await db.delete(schema.orderItems);
  await db.delete(schema.orders);
  await db.delete(schema.cartItems);
  await db.delete(schema.testRides);
  await db.delete(schema.leads);
  await db.delete(schema.motorcycles);
  await db.delete(schema.parts);
  await db.delete(schema.dealers);
  await db.delete(schema.posts);

  await db.insert(schema.motorcycles).values(motorcycles);
  await db.insert(schema.parts).values(parts);
  await db.insert(schema.dealers).values(dealers);
  await db.insert(schema.posts).values(posts);

  console.log(
    `seed ok: ${motorcycles.length} motos, ${parts.length} peças, ${dealers.length} concessionárias, ${posts.length} posts`,
  );
}

await seed();
